# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/huang/zhiauth

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/huang/zhiauth

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/huang/zhiauth/CMakeFiles /home/huang/zhiauth//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/huang/zhiauth/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named zhiauth_core

# Build rule for target.
zhiauth_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zhiauth_core
.PHONY : zhiauth_core

# fast build rule for target.
zhiauth_core/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/build
.PHONY : zhiauth_core/fast

#=============================================================================
# Target rules for targets named zhiauth_kcp_worker

# Build rule for target.
zhiauth_kcp_worker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zhiauth_kcp_worker
.PHONY : zhiauth_kcp_worker

# fast build rule for target.
zhiauth_kcp_worker/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_kcp_worker.dir/build.make CMakeFiles/zhiauth_kcp_worker.dir/build
.PHONY : zhiauth_kcp_worker/fast

src/bridge/auth_bridge.o: src/bridge/auth_bridge.cpp.o
.PHONY : src/bridge/auth_bridge.o

# target to build an object file
src/bridge/auth_bridge.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/bridge/auth_bridge.cpp.o
.PHONY : src/bridge/auth_bridge.cpp.o

src/bridge/auth_bridge.i: src/bridge/auth_bridge.cpp.i
.PHONY : src/bridge/auth_bridge.i

# target to preprocess a source file
src/bridge/auth_bridge.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/bridge/auth_bridge.cpp.i
.PHONY : src/bridge/auth_bridge.cpp.i

src/bridge/auth_bridge.s: src/bridge/auth_bridge.cpp.s
.PHONY : src/bridge/auth_bridge.s

# target to generate assembly for a file
src/bridge/auth_bridge.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/bridge/auth_bridge.cpp.s
.PHONY : src/bridge/auth_bridge.cpp.s

src/common/logger.o: src/common/logger.cpp.o
.PHONY : src/common/logger.o

# target to build an object file
src/common/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/common/logger.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_kcp_worker.dir/build.make CMakeFiles/zhiauth_kcp_worker.dir/src/common/logger.cpp.o
.PHONY : src/common/logger.cpp.o

src/common/logger.i: src/common/logger.cpp.i
.PHONY : src/common/logger.i

# target to preprocess a source file
src/common/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/common/logger.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_kcp_worker.dir/build.make CMakeFiles/zhiauth_kcp_worker.dir/src/common/logger.cpp.i
.PHONY : src/common/logger.cpp.i

src/common/logger.s: src/common/logger.cpp.s
.PHONY : src/common/logger.s

# target to generate assembly for a file
src/common/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/common/logger.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_kcp_worker.dir/build.make CMakeFiles/zhiauth_kcp_worker.dir/src/common/logger.cpp.s
.PHONY : src/common/logger.cpp.s

src/common/sqlite_handler.o: src/common/sqlite_handler.cpp.o
.PHONY : src/common/sqlite_handler.o

# target to build an object file
src/common/sqlite_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/common/sqlite_handler.cpp.o
.PHONY : src/common/sqlite_handler.cpp.o

src/common/sqlite_handler.i: src/common/sqlite_handler.cpp.i
.PHONY : src/common/sqlite_handler.i

# target to preprocess a source file
src/common/sqlite_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/common/sqlite_handler.cpp.i
.PHONY : src/common/sqlite_handler.cpp.i

src/common/sqlite_handler.s: src/common/sqlite_handler.cpp.s
.PHONY : src/common/sqlite_handler.s

# target to generate assembly for a file
src/common/sqlite_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/common/sqlite_handler.cpp.s
.PHONY : src/common/sqlite_handler.cpp.s

src/rpc_vfs/crypto_box.o: src/rpc_vfs/crypto_box.cpp.o
.PHONY : src/rpc_vfs/crypto_box.o

# target to build an object file
src/rpc_vfs/crypto_box.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/rpc_vfs/crypto_box.cpp.o
.PHONY : src/rpc_vfs/crypto_box.cpp.o

src/rpc_vfs/crypto_box.i: src/rpc_vfs/crypto_box.cpp.i
.PHONY : src/rpc_vfs/crypto_box.i

# target to preprocess a source file
src/rpc_vfs/crypto_box.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/rpc_vfs/crypto_box.cpp.i
.PHONY : src/rpc_vfs/crypto_box.cpp.i

src/rpc_vfs/crypto_box.s: src/rpc_vfs/crypto_box.cpp.s
.PHONY : src/rpc_vfs/crypto_box.s

# target to generate assembly for a file
src/rpc_vfs/crypto_box.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/rpc_vfs/crypto_box.cpp.s
.PHONY : src/rpc_vfs/crypto_box.cpp.s

src/rpc_vfs/ikcp.o: src/rpc_vfs/ikcp.c.o
.PHONY : src/rpc_vfs/ikcp.o

# target to build an object file
src/rpc_vfs/ikcp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/rpc_vfs/ikcp.c.o
.PHONY : src/rpc_vfs/ikcp.c.o

src/rpc_vfs/ikcp.i: src/rpc_vfs/ikcp.c.i
.PHONY : src/rpc_vfs/ikcp.i

# target to preprocess a source file
src/rpc_vfs/ikcp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/rpc_vfs/ikcp.c.i
.PHONY : src/rpc_vfs/ikcp.c.i

src/rpc_vfs/ikcp.s: src/rpc_vfs/ikcp.c.s
.PHONY : src/rpc_vfs/ikcp.s

# target to generate assembly for a file
src/rpc_vfs/ikcp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/rpc_vfs/ikcp.c.s
.PHONY : src/rpc_vfs/ikcp.c.s

src/rpc_vfs/kcp_worker_main.o: src/rpc_vfs/kcp_worker_main.cpp.o
.PHONY : src/rpc_vfs/kcp_worker_main.o

# target to build an object file
src/rpc_vfs/kcp_worker_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_kcp_worker.dir/build.make CMakeFiles/zhiauth_kcp_worker.dir/src/rpc_vfs/kcp_worker_main.cpp.o
.PHONY : src/rpc_vfs/kcp_worker_main.cpp.o

src/rpc_vfs/kcp_worker_main.i: src/rpc_vfs/kcp_worker_main.cpp.i
.PHONY : src/rpc_vfs/kcp_worker_main.i

# target to preprocess a source file
src/rpc_vfs/kcp_worker_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_kcp_worker.dir/build.make CMakeFiles/zhiauth_kcp_worker.dir/src/rpc_vfs/kcp_worker_main.cpp.i
.PHONY : src/rpc_vfs/kcp_worker_main.cpp.i

src/rpc_vfs/kcp_worker_main.s: src/rpc_vfs/kcp_worker_main.cpp.s
.PHONY : src/rpc_vfs/kcp_worker_main.s

# target to generate assembly for a file
src/rpc_vfs/kcp_worker_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_kcp_worker.dir/build.make CMakeFiles/zhiauth_kcp_worker.dir/src/rpc_vfs/kcp_worker_main.cpp.s
.PHONY : src/rpc_vfs/kcp_worker_main.cpp.s

src/rpc_vfs/vfs_io_worker.o: src/rpc_vfs/vfs_io_worker.cpp.o
.PHONY : src/rpc_vfs/vfs_io_worker.o

# target to build an object file
src/rpc_vfs/vfs_io_worker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_kcp_worker.dir/build.make CMakeFiles/zhiauth_kcp_worker.dir/src/rpc_vfs/vfs_io_worker.cpp.o
.PHONY : src/rpc_vfs/vfs_io_worker.cpp.o

src/rpc_vfs/vfs_io_worker.i: src/rpc_vfs/vfs_io_worker.cpp.i
.PHONY : src/rpc_vfs/vfs_io_worker.i

# target to preprocess a source file
src/rpc_vfs/vfs_io_worker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_kcp_worker.dir/build.make CMakeFiles/zhiauth_kcp_worker.dir/src/rpc_vfs/vfs_io_worker.cpp.i
.PHONY : src/rpc_vfs/vfs_io_worker.cpp.i

src/rpc_vfs/vfs_io_worker.s: src/rpc_vfs/vfs_io_worker.cpp.s
.PHONY : src/rpc_vfs/vfs_io_worker.s

# target to generate assembly for a file
src/rpc_vfs/vfs_io_worker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_kcp_worker.dir/build.make CMakeFiles/zhiauth_kcp_worker.dir/src/rpc_vfs/vfs_io_worker.cpp.s
.PHONY : src/rpc_vfs/vfs_io_worker.cpp.s

src/rpc_vfs/vfs_server.o: src/rpc_vfs/vfs_server.cpp.o
.PHONY : src/rpc_vfs/vfs_server.o

# target to build an object file
src/rpc_vfs/vfs_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/rpc_vfs/vfs_server.cpp.o
.PHONY : src/rpc_vfs/vfs_server.cpp.o

src/rpc_vfs/vfs_server.i: src/rpc_vfs/vfs_server.cpp.i
.PHONY : src/rpc_vfs/vfs_server.i

# target to preprocess a source file
src/rpc_vfs/vfs_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/rpc_vfs/vfs_server.cpp.i
.PHONY : src/rpc_vfs/vfs_server.cpp.i

src/rpc_vfs/vfs_server.s: src/rpc_vfs/vfs_server.cpp.s
.PHONY : src/rpc_vfs/vfs_server.s

# target to generate assembly for a file
src/rpc_vfs/vfs_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/rpc_vfs/vfs_server.cpp.s
.PHONY : src/rpc_vfs/vfs_server.cpp.s

src/system/sys_control.o: src/system/sys_control.cpp.o
.PHONY : src/system/sys_control.o

# target to build an object file
src/system/sys_control.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/system/sys_control.cpp.o
.PHONY : src/system/sys_control.cpp.o

src/system/sys_control.i: src/system/sys_control.cpp.i
.PHONY : src/system/sys_control.i

# target to preprocess a source file
src/system/sys_control.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/system/sys_control.cpp.i
.PHONY : src/system/sys_control.cpp.i

src/system/sys_control.s: src/system/sys_control.cpp.s
.PHONY : src/system/sys_control.s

# target to generate assembly for a file
src/system/sys_control.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/system/sys_control.cpp.s
.PHONY : src/system/sys_control.cpp.s

src/system/ufw_manager.o: src/system/ufw_manager.cpp.o
.PHONY : src/system/ufw_manager.o

# target to build an object file
src/system/ufw_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/system/ufw_manager.cpp.o
.PHONY : src/system/ufw_manager.cpp.o

src/system/ufw_manager.i: src/system/ufw_manager.cpp.i
.PHONY : src/system/ufw_manager.i

# target to preprocess a source file
src/system/ufw_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/system/ufw_manager.cpp.i
.PHONY : src/system/ufw_manager.cpp.i

src/system/ufw_manager.s: src/system/ufw_manager.cpp.s
.PHONY : src/system/ufw_manager.s

# target to generate assembly for a file
src/system/ufw_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zhiauth_core.dir/build.make CMakeFiles/zhiauth_core.dir/src/system/ufw_manager.cpp.s
.PHONY : src/system/ufw_manager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... zhiauth_core"
	@echo "... zhiauth_kcp_worker"
	@echo "... src/bridge/auth_bridge.o"
	@echo "... src/bridge/auth_bridge.i"
	@echo "... src/bridge/auth_bridge.s"
	@echo "... src/common/logger.o"
	@echo "... src/common/logger.i"
	@echo "... src/common/logger.s"
	@echo "... src/common/sqlite_handler.o"
	@echo "... src/common/sqlite_handler.i"
	@echo "... src/common/sqlite_handler.s"
	@echo "... src/rpc_vfs/crypto_box.o"
	@echo "... src/rpc_vfs/crypto_box.i"
	@echo "... src/rpc_vfs/crypto_box.s"
	@echo "... src/rpc_vfs/ikcp.o"
	@echo "... src/rpc_vfs/ikcp.i"
	@echo "... src/rpc_vfs/ikcp.s"
	@echo "... src/rpc_vfs/kcp_worker_main.o"
	@echo "... src/rpc_vfs/kcp_worker_main.i"
	@echo "... src/rpc_vfs/kcp_worker_main.s"
	@echo "... src/rpc_vfs/vfs_io_worker.o"
	@echo "... src/rpc_vfs/vfs_io_worker.i"
	@echo "... src/rpc_vfs/vfs_io_worker.s"
	@echo "... src/rpc_vfs/vfs_server.o"
	@echo "... src/rpc_vfs/vfs_server.i"
	@echo "... src/rpc_vfs/vfs_server.s"
	@echo "... src/system/sys_control.o"
	@echo "... src/system/sys_control.i"
	@echo "... src/system/sys_control.s"
	@echo "... src/system/ufw_manager.o"
	@echo "... src/system/ufw_manager.i"
	@echo "... src/system/ufw_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

